spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/GCCoffee?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #2022-10-5_yeoooo : mysql을 이용할 떄 serverTimezone을 UTC로 설정하면 의도하는 날짜와 실제 저장 날짜가 일치하지 않는 문제가 있음.
    #                   ServerTimezone = UTC(=> Asia/Seoul)
    username: root
    password: 8354dnjsdl

# FOR H2 DATABASE
#    url: jdbc:h2:tcp://localhost/~/dev/java/Grids-Circles-Clone-APIServer
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:

  security:
    user:
      name: user
      password: 1234


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    generate-ddl: true

  sql:
    init:
      platform: mysql
      encoding: UTF-8
      mode: always
grpc:
  server:
    port: 9090

  client:
    management:
      negotiation-type: plaintext
      address: "static://localhost:9090"


#    test:
##      address: "static://localhost:8443"
#      address:
#      negotiationtype: plaintext


